#!/bin/sh

echo "Searching flutter's pid ..."

cat /tmp/flutter.pid

if [ $? -eq 0 ]; then
	echo ""
	echo "Firing HOT RELOAD Event ..."
	kill -USR1 "$(cat /tmp/flutter.pid)"
else
	echo "Unable to detect /tmp/flutter.pid file!"
	echo "You must run your flutter project with --pid-file flag."
	echo "Like: flutter run --pid-file /tmp/flutter.pid"
	exit 1
fi

